inveniosoftware/invenio-github

- examples/app.py
- invenio_github/api.py
- invenio_github/config.py
- invenio_github/receivers.py
- invenio_github/templates/invenio_github/settings/index.html
- invenio_github/templates/invenio_github/settings/view.html
- invenio_github/views/github.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
> api: configurable deposit class

- docs/conf.py
> docs: sphinx v1.4 fix

- .travis.yml
- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_github/version.py
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
> release: v1.0.0a1

- invenio_github/version.py
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
> version: post-release bump

- invenio_github/translations/en/LC_MESSAGES/messages.po
- invenio_github/translations/messages.pot
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
> translations: initial message catalog

- invenio_github/admin.py
- setup.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
> admin: addition of admin model views

- invenio_github/api.py
- invenio_github/config.py
- invenio_github/models.py
- invenio_github/views/badge.py
- invenio_github/views/github.py
- tests/test_badge.py
* Fix incorrect use of model function-call/property.
> badges: handle non-existent releases

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_github/version.py
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
> release: v1.0.0a7

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_github/api.py
- invenio_github/models.py
- invenio_github/tasks.py
- invenio_github/version.py
- invenio_github/views/github.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
> global: repository syncing issues fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_github/version.py
- setup.py
> release: v1.0.0a9

- .editorconfig
- docs/conf.py
- run-tests.sh
- tests/__init__.py
- tests/conftest.py
- tests/fixtures.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
> installation: isort glob fix

- invenio_github/api.py
- invenio_github/handlers.py
- invenio_github/models.py
- invenio_github/tasks.py
- invenio_github/utils.py
* Converts the user ID to an integer throughout various API calls.
(closes #46)
> global: user ID integer conversion

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_github/version.py
> release: v1.0.0a13

- CHANGES.rst
- invenio_github/api.py
- invenio_github/version.py
> Fix alternate links handling for zipball and release v1.0.0a23

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_github/api.py
- invenio_github/templates/invenio_github/settings/view.html
- invenio_github/version.py
- invenio_github/views/github.py
- global: fix CITATION.cff creation link
- release: v1.0.0a28
> Fix CITATION.cff creation link and v1.0.0a28 release

- CHANGES.rst
- invenio_github/__init__.py
> release: v1.0.0b1

- CHANGES.rst
- invenio_github/__init__.py
> release: v1.0.0b2

- CHANGES.rst
- invenio_github/__init__.py
> release: v1.0.0b3

- CHANGES.rst
- invenio_github/__init__.py
> release: v1.0.0b4

- CHANGES.rst
- invenio_github/__init__.py
> release: v1.0.0b5

- invenio_github/api.py
- invenio_github/views/badge.py
- invenio_github/views/github.py
closes https://github.com/inveniosoftware/invenio-github/issues/101
> badges: updated badges to new architecture

- CHANGES.rst
- invenio_github/__init__.py
> release: v1.0.0b6

- CHANGES.rst
- invenio_github/__init__.py
> release: v1.0.0

- invenio_github/assets/semantic-ui/js/invenio_github/index.js
- invenio_github/models.py
- invenio_github/templates/semantic-ui/invenio_github/helpers.html
- invenio_github/templates/semantic-ui/invenio_github/settings/helpers.html
- invenio_github/templates/semantic-ui/invenio_github/settings/index.html
- invenio_github/templates/semantic-ui/invenio_github/settings/index_item.html
- invenio_github/templates/semantic-ui/invenio_github/settings/view.html
- invenio_github/views/github.py
Closes https://github.com/inveniosoftware/invenio-github/issues/115
> ui: layout and styling improvements

- CHANGES.rst
- invenio_github/__init__.py
> release: v1.0.1

- invenio_github/assets/semantic-ui/js/invenio_github/index.js
> api: add csrftoken in requests

- CHANGES.rst
- invenio_github/__init__.py
> release: v1.0.2

- invenio_github/assets/semantic-ui/js/invenio_github/index.js
- invenio_github/templates/semantic-ui/invenio_github/settings/view.html
- invenio_github/views/badge.py
- setup.cfg
* assets: reject hanging sync request
* closes https://github.com/zenodo/rdm-project/issues/275
* closes https://github.com/zenodo/rdm-project/issues/276
> badges: fix unreachable pid for record

- CHANGES.rst
- invenio_github/__init__.py
- invenio_github/api.py
hiding issues in https://zenodo-sentry.web.cern.ch/sentry/zenodo-rdm/issues/29446182/?environment=dev
> Remove all catch block

- CHANGES.rst
- invenio_github/__init__.py
- invenio_github/views/badge.py
* closes https://github.com/zenodo/rdm-project/issues/292
* closes https://github.com/zenodo/rdm-project/issues/294
> Badge hotfix

- CHANGES.rst
- invenio_github/__init__.py
- invenio_github/views/badge.py
* closes https://github.com/zenodo/rdm-project/issues/341
> views: get correct record identifier

- invenio_github/templates/semantic-ui/invenio_github/settings/view.html
closes https://github.com/zenodo/rdm-project/issues/378
> view: fixed wrong accesses to event.payload.

- invenio_github/config.py
- invenio_github/tasks.py
closes https://github.com/zenodo/zenodo-rdm/issues/407
> config: added default configs for citation cff support.

- invenio_github/templates/semantic-ui/invenio_github/settings/view.html
- invenio_github/views/badge.py
- invenio_github/views/github.py
closes https://github.com/zenodo/rdm-project/issues/422
> ui: fixed rendering of releases without event.

- invenio_github/api.py
- invenio_github/tasks.py
closes https://github.com/zenodo/rdm-project/issues/434
> release: fetch owner from remote.

- invenio_github/api.py
- invenio_github/errors.py
- invenio_github/views/github.py
closes https://github.com/zenodo/rdm-project/issues/427
> api: fix shared repos filtering and permissions.

- invenio_github/oauth/remote_app.py
closes https://github.com/zenodo/rdm-project/issues/555
> oauth: modified user scope to read-only.

- invenio_github/api.py
- Fix repository sync for users that are part of an organization.
closes https://github.com/inveniosoftware/invenio-github/issues/169
> api: fix repository sync by org users

- .github/workflows/pypi-publish.yml
- .github/workflows/tests.yml
- CHANGES.rst
- invenio_github/__init__.py
- setup.cfg
- setup: pin dependencies
- setup: change to reusable workflows
- release: v1.5.3
> pin dependencies

- .github/workflows/pypi-publish.yml
- CHANGES.rst
- invenio_github/__init__.py
- fix: publish with translations
- release: v1.5.4
> fix compile catalog

- .github/workflows/tests.yml
- CHANGES.rst
- invenio_github/__init__.py
- invenio_github/api.py
- invenio_github/errors.py
- invenio_github/tasks.py
- invenio_github/views/github.py
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
> I18n-transkations-backport
